server:  
  port: ${PORT:2222}
spring:  
  application:
    name: account-service
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
ribbon:
  eureka:
    enabled: true